apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  labels:
    app: ingress-nginx
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
    external-dns.alpha.kubernetes.io/hostname: ingress.revanthkube.ml
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: http
  - port: 443
    name: https
    targetPort: https
  selector:
    app: ingress-nginx
#--- 
#kind: ConfigMap
#apiVersion: v1
#metadata:
#  name: nginx-configuration
#  labels: 
#    app: ingress-nginx
#data:
#  use-proxy-prtocol: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: echoheaders-default
  labels:
    app: echoheaders
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30302
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: echoheaders
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Service.db_name }}
spec:
  type: {{ .Values.Service.db_svc_type }}
  ports:
  - port: {{ .Values.Service.db_svc_port }}
    targetPort: {{ .Values.Service.db_svc_port }}
  selector:
    app: {{ .Values.Service.db_name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Service.app_name }}
  labels:
    run: {{ .Values.Service.app_name }}
spec:
  type: {{ .Values.Service.app_svc_type }}
  ports:
  - port: {{ .Values.Service.app_svc_port}}
#    nodePort: 30303
    targetPort: {{ .Values.Service.app_port }}
#    protocol: TCP
#    name: http
  selector:
    app: {{ .Values.Service.app_name }}


